version: '3.4'

services:
  wilowsmithcsv:
    image: wilowsmithcsv
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9000:9000
